---
- name: Install NGINX
  apt: name=nginx state=present

- name: Setup NGINX configuration
  template: src=wordpress.conf dest=/etc/nginx/sites-available/{{ website_name }}.conf
  notify: restart nginx
